
trigger:
# When new commits are pushed onto the main branch.
- master

pool:
  vmImage: ubuntu-latest

steps:
# Setup environment.
- task: NodeTool@0
  inputs:
    versionSpec: '18'
    checkLatest: true

- task: Bash@3
  env:
    # To enable M365 account login by environment variables and non-interactive mode.
    CI_ENABLED: 'true'
    # To specify the environment name which will be used as an option below.
    # You can change it to use your own environment name.
    TEAMSFX_ENV_NAME: 'dev'
    # To specify the version of TTK CLI for use.
    TEAMSFX_CLI_VERSION: 2.*
  inputs:
    targetType: 'inline'
    script: |
      set -evuxo pipefail
      npm install @microsoft/teamsfx-cli@${TEAMSFX_CLI_VERSION}

      # Login Azure by service principal
      npx teamsfx account login azure --service-principal true --username $(AZURE_SERVICE_PRINCIPAL_NAME) --password $(AZURE_SERVICE_PRINCIPAL_PASSWORD) --tenant $(AZURE_TENANT_ID)

      # Deploy to hosting environment.
      npx teamsfx deploy --env ${TEAMSFX_ENV_NAME}