on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      CI_ENABLED: true
      TEAMSFX_CLI_VERSION: "3.0.0-alpha.38a3757c0.0"
      BOT_AZURE_APP_SERVICE_RESOURCE_ID: ${{vars.BOT_AZURE_APP_SERVICE_RESOURCE_ID}}
      TEAMS_APP_ID: ${{vars.TEAMS_APP_ID}}
      BOT_ID: ${{vars.BOT_ID}}
      APP_NAME_SUFFIX: ${{vars.APP_NAME_SUFFIX}}

    steps:
      - name: "Checkout Github Action"
        uses: actions/checkout@master

      - name: Setup Node 18.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: install cli
        run: |
          npm install @microsoft/teamsapp-cli@${{env.TEAMSFX_CLI_VERSION}}

      - name: Login Azure by service principal
        run: |
          npx teamsapp account login azure --username ${{vars.AZURE_SERVICE_PRINCIPAL_NAME}}  \
          --service-principal true \
          --tenant ${{vars.AZURE_TENANT_ID}} \
          --password ${{secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD}} \
          --interactive false

      - name: Deploy to hosting environment
        run: |
          npx teamsapp deploy --ignore-env-file true \
          --interactive false

      - name: Package app
        run: |
          npx teamsapp package --ignore-env-file true

      - name: unzip
        run: |
          cd appPackage/build
          unzip -o -d . appPackage.zip
          cd -

      - name: upload appPackage
        uses: actions/upload-artifact@v4
        with:
          name: appPackage
          path: |
            appPackage/build/manifest.json
            appPackage/build/color.png
            appPackage/build/outline.png
